spring:
  application:
    name: car-rental-service

  datasource:
    url: jdbc:postgresql://localhost:5432/car_rental_db?options=-c%20TimeZone=Europe/Kiev
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: 180000
  refresh-token-expiration-ms: 86400000

stripe:
  api-key: ${STRIPE_API_KEY}
  success-url: http://localhost:8080/api/payments/success
  cancel-url: http://localhost:8080/api/payments/cancel

scheduler:
  fixed-delay: 60000

bot:
  username: "MyCarRentalNotificationBot"
  token: ${RENTAL_BOT_TOKEN}
  admin-chat-id: 1456810112

rental:
  fine:
    late-return-multiplier: 1.5

logging:
  level:
    root: info
    com.example.carrental: INFO

  file:
    name: ./logs/application.log

  logback:
    rollingpolicy:
      file-name-pattern: ./logs/archived/application-%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 7
      clean-history-on-start: true

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level) [%thread] %clr(%logger{36}){cyan}: %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36}: %msg%n"